version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "monthly"
    groups:
      all:
        patterns: ["*"]
        update-types: ["major", "minor", "patch"]
