name: Build Image from Dockerfile
on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Publish Image
      uses: matootie/github-docker@v3.1.0
      with:
        accessToken: ${{ secrets.GITHUB_TOKEN }}
        imageName: manylinux2010_x86_64-hdf5
        containerRegistry: true
