name: Build Image from Dockerfile
on:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - '.github/workflows/build-image.yml'
      - 'CMakeLists.txt'
  pull_request:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - '.github/workflows/build-image.yml'
      - 'CMakeLists.txt'
  workflow_dispatch:
    inputs:
      manylinux_tag:
        description: 'Manylinux tag to build'
        required: true
        default: "2025-06-19-87542c8"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  build:
    name: Build image for ${{ matrix.arch }}
    runs-on: ubuntu-24.04${{ matrix.arch == 'aarch64' && '-arm' || '' }}
    permissions:
      packages: write
      contents: read
    strategy:
      matrix:
        include:
          - arch: x86_64
            plat: linux/amd64
          - arch: aarch64
            plat: linux/arm64
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v5
      with:
        persist-credentials: false
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5.8.0
      with:
        images: |
          ghcr.io/cantera/cantera-base-manylinux_2_28-${{ matrix.arch }}
        tags: |
          type=raw,value=latest,enable={{is_default_branch}}
          type=ref,event=branch
          type=ref,event=pr
    - name: Build args
      id: build-args
      run: |
        {
          echo 'BUILD_ARGS<<EOF'
          echo TARGET_ARCH=${{ matrix.arch }}
          if [ -n "$MANYLINUX_TAG_INPUT" ]; then
            echo MANYLINUX_TAG=$MANYLINUX_TAG_INPUT
          fi
          echo EOF
        } >> $GITHUB_OUTPUT
      env:
        MANYLINUX_TAG_INPUT: ${{ github.event.inputs.manylinux_tag }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
      with:
        platforms: ${{ matrix.plat }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: ${{ steps.build-args.outputs.BUILD_ARGS }}
        cache-from: ${{ github.event_name != 'pull_request' && 'type=gha' || '' }}
        cache-to: ${{ github.event_name != 'pull_request' && 'type=gha,mode=max' || '' }}
