name: Build Image from Dockerfile
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_x86_64:
    name: Build image for x86_64
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64
        push: ${{ github.ref_name == 'main' }}
        tags: ghcr.io/cantera/manylinux2014_x86_64-hdf5-boost
        build-args: |
          TARGET_ARCH=x86_64
        cache-from: type=gha
        cache-to: type=gha,mode=max

  build_aarch64:
    name: Build image for aarch64
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        platforms: linux/arm64
        push: ${{ github.ref_name == 'main' }}
        tags: ghcr.io/cantera/manylinux2014_aarch64-hdf5-boost
        build-args: |
          TARGET_ARCH=aarch64
        cache-from: type=gha
        cache-to: type=gha,mode=max
