name: Build Image from Dockerfile
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build image for ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: x86_64
            plat: linux/amd64
          - arch: aarch64
            plat: linux/arm64
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up QEMU
      if: matrix.arch == 'aarch64'
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        platforms: ${{ matrix.plat }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: ghcr.io/cantera/manylinux_2_28-cantera-base
        build-args: |
          TARGET_ARCH=${{ matrix.arch }}
        target: builder
        cache-from: type=gha
        cache-to: type=gha,mode=max
